[window]
padding = { x = 20, y = 20}
title = "AraAratty"
dynamic_title = false

[font]
size = 16

[font.bold]
family = "IosevkaTermNerdFontMono"
style = "Bold"

[font.bold_italic]
family = "IosevkaTermNerdFontMono"
style = "Bold Italic"

[font.italic]
family = "IosevkaTermNerdFontMono"
style = "Italic"

[font.normal]
family = "IosevkaTermNerdFontMono"
style = "Regular"

[colors]
selection = { text = "#282C34", background = "#DCDFE4"}

[colors.primary]
foreground = "#DCDFE4"
background = "#282C34"

[colors.normal]
black = "#282C34"
red = "#E06C75"
green = "#98C379"
yellow = "#E5C07B"
blue = "#61AFEF"
magenta = "#C678DD"
cyan = "#56B6C2"
white = "#DCDFE4"

[colors.bright]
black = "#DCDFE4"
red = "#E06C75"
green = "#98C379"
yellow = "#E5C07B"
blue = "#61AFEF"
magenta = "#C678DD"
cyan = "#56B6C2"
white = "#DCDFE4"
